### ISSUE TITLE
feat: add tracking in-game stats (Game Planner)

### ISSUE THREAD

**Issue by imnaiyar** [imnaiyar/SkyHelper#75]
This is in progress. Below is progress tracker of its implementation ~~Ah, this may take more work to do but putting it here in case I ever decide to implement this.~~

# TODO
- [ ] add links to skywiki for supported items
- [ ] add markings shards cleared and updating currencies accordingly
- [ ] season pass bought/recieved
- [ ] dailies dones
- [ ] In-depth breakdown for specific spent currencies (preferably via modal)
- [ ] add more information on spirits page (ts total visits, ts dates-duration, etc)
- [ ] Find a way to add all seasons/events in filter select (currently cuts off at 25 due to discord limits) [^1]
- [ ] add bought/unlocked/etc filter for items
- [ ] calculator and it's button on respective active event/season
- [x] Sentry scope capture is isolately, like it is in interaction create 
- [x] buying/locking item should dynamically changes currencies
- [x] With addition of filters, sometimes /string-store buffer gets full, think of somethinng (current solution is not passing filter in some places)
- [x] user currencies
- [x] Export/import data from/to sky-planner.com website to sync progress between them [^4]
- [x] user stats (and maybe profile card)
- [x] Shop IAP/Stor bought recieved
- [x] WLs (and buffs) ...same
- [x] Tree `Modify` handler (selecting items, in events, spirit, seasons, ...?)
- [x] something for wing buff (idk if something separate is needed or not)
- [x] spirit name on tree pic gets large for smaller nodes (also maybe add subtitle under the name, possibly to add extra details like vist numbers);
- [x] spirit in tree view is sometimes not resolved properly (may have to also look into event instance spirits). Also have a option to not show "view" spirit section
- [x] update /tracker commands and think of a name an bunch of things to do before beta
- [x] go to source for items
- [x] item highlights (possibly using filters), also maybe iap highlights
- [x] make home btns go  to display's home instead of actual one's
- [x] Permanent shop display
  - [x]  Nesting Workshop
  - [x] Aviary Event Store
  - [x] Concert Hall
  - [x] Harmony Hall
  - [x] Secret Area
  - [x] IAPs
- [x] Rotates indicator shows in all rotation displays, remember  to fix it
- [x] separate property for item's icon (`emoji`), also use skygame-planner image path for item for image generation [^2]
- [x] season display
- [x] Special Visits (Returning Spirits)
- [x] TS Display
- [x] Realm display
- [x] Spirit display
- [x] Events display
- [x] Area displays
- [x] Tree generator behaving awkwardly with some trees
- [x] A way to go to regular/seasonal spirits list from realms (?season too). possibly by having additional filters (implemented by adding filters)
- [x] ~~A mapped type for filters for different tabs, so it is type safe~~ instead added unified filter manager [^3]
- [x] ~~can't put userid in custom_id serialization, hitting internal server errors (find a way to circumvent it)~~ Resolved with #319 

This feature should ideally have:
- A way to track spirit's progress (items unlocked, nodes)
- A way to track realms, season progress (possibly inferring from spirit's unlocked items)
- A way to track wls, candles, heart
- And possibly maybe have something to track heart trades (not too up on the priority list but would be a good feature to have)

[^1]: Discord only allows 25 options in selects, and there are obviously more than 25 seasons and events, currently in the process of building and testing, it cuts off upto 25, but this will abviously not be ideal in production. Some solution for this needs to be thought of

[^2]: Currently some data structures overwrites the `icon` property to add emoji ids, this is not ideal. For example, for new items, if the emoji is not updated, then this will be image url and the cose always assuming this to be emoji id will break. Having a separately defined emoji field is both better for consistency and to avoid confusions as described above

[^3]: Although this was added, this comes with some caveats. As all the states are stored in custom_id by compact buffers using /string-store, there's only so much data it can store with 100-char limits of custom_id, and filters can be so large in some places (e.g `item`), hence each of filter type is limited to only three selections at a time to avoid full buffers

[^4]: I had this in mind before i even began writing this, but there may be few caveats with this. Import data to the bot shouldn't be a too much of a difference. Though exporting back to website may not be entirely 1:1. Specifically, some website specific preferences such as filters..etc wil consequently be ignored and not saved by the bot. So these things (and maybe more that i may be forgetting) could be lost. This will be conveyed properly from the bot when stable is released
